### ISSUE TITLE
No Internet connection Through VPN

### ISSUE THREAD

**Issue by mindrunner** [mobilejazz/docker-ipsec-vpn-server#12]
I set up everything according to the documentation. Added users. Connection is established, but there is no Internet Access from my android device. 

How can I start debugging the issue?

**Comment by mindrunner** [comment]
Android On-Demand VPN: Connects and has Internet
Android Always-On VPN: Connects and has no Internet
macOS VPN: Does not connect

What can be wrong here?

**Comment by just1689** [comment]
Have you tried using the built-in Android config (no app)?
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android

**Comment by mindrunner** [comment]
Yes, exactly!

**Comment by mindrunner** [comment]
May I ask why are you closing this?

**Comment by just1689** [comment]
Ola. (I'm not affiliated with the project).

You mentioned:

> Android On-Demand VPN: Connects and has Internet
> Android Always-On VPN: Connects and has no Internet
> macOS VPN: Does not connect

May I ask about the first two? Are those just different Android clients? Or is the "Always-on" a Wifi connection you're using? I know at malls in my country they have "free wifi" which is called Always On? I am wondering what it means if your notes?

The fact that it works in one client on Android is good news. That's a good starting point.
