### ISSUE TITLE
Reserving Static IPs for Users

### ISSUE THREAD

**Issue by shankscoder** [mobilejazz/docker-ipsec-vpn-server#13]
This isn't an issue but an FYI for others who want to know how to do this. Since the Wiki isn't working, figured this would suffice.

### If you intend to pin specific IPs for certain users, it's pretty easy.

Assuming you have a running VPN setup:
1. Create the user account using the ./adduser.sh tool
2. Open the `./etc/ppp/chap-secrets` file _(the etc folder that's passed to the docker container, not the system host)_
     It should have contents as follows:
>
     "user1" l2tpd "somepassphrase1" *
     "user2" l2tpd "somepassphrase2" *
     ...

The syntax each line is:
`user server password ip`

3. To set a static IP for a specific user, replace the `*` with the specific IP you want to pin for that user.
4. Restart the VPN server
5. Reconnect the VPN client and it should get the new assigned IP

**Comment by jgimenez** [comment]
Thanks for sharing!
