### ISSUE TITLE
no ipV6 protection?

### ISSUE THREAD

**Issue by carterw** [mobilejazz/docker-ipsec-vpn-server#15]
I got this up and running on a server and connect to it from a Windows machine. Unfortunately when I run tests on the various whatismyip websites they show that while my ipV4 address is masked (shows as the address of the VPN server), my ipV6 address is still exposed.

**Comment by jgimenez** [comment]
Yes, this VPN is IPv4 only, please feel free to submit a PR if you want to set up IPv6 as well
