### ISSUE TITLE
Doesn't work on ios13

### ISSUE THREAD

**Issue by KELiON** [mobilejazz/docker-ipsec-vpn-server#22]
I used this VPN server and it was perfect, but after updating to iOS13 it stoped working. 

I still can connect to the server, but internet doesn't work, it just shows endless loader in Safari and shows error "Safari could not open the page because the server stopped responding".

The same configuration works great on iOS12 and on MacOS, but does not on iOS13.

Do you have any ideas how to fix the issue?

**Comment by sdempsay** [comment]
Could it be related to this bug?

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ios-13-and-macos-1015

**Comment by KELiON** [comment]
@sdempsay exactly, changing `sha2-truncbug` to `no` solved the problem. Should be it changed in this repo?

**Comment by jgimenez** [comment]
Makes sense, I'll try to apply the change here. PRs are welcome, of course

**Comment by jgimenez** [comment]
Fixed in 52ce3654725ce8d9734fd18a96c8e8626258376d

**Comment by KELiON** [comment]
👍 thanks @jgimenez
