### ISSUE TITLE
Create Backup

### ISSUE THREAD

**Issue by Avalarion** [mobilejazz/docker-ipsec-vpn-server#3]
Hey there,

awesome toolkit, works out of the box.

I have a short question: I would love to Backup my Maschine from time to time. Where are the user information saved? How am I able to save them or the whole container?

Greetings,

Bastian

**Comment by jgimenez** [comment]
Hi, you will see when you run the start script that an etc directory will be created, that is the only thing to be backed up

**Comment by Avalarion** [comment]
Thank you very much =).
