### ISSUE TITLE
Listing active connections and IPs on server

### ISSUE THREAD

**Issue by shankscoder** [mobilejazz/docker-ipsec-vpn-server#5]
Hi,
Is there a way to get a list of active connections and the local IPs they're connected as?

We're trying to create a private network to monitor some devices, and being able to list the active devices and their IPS would be super helpful for our admins. Is this possible?

**Comment by shankscoder** [comment]
Ahh, sorry I found the answer partially.

`docker exec -it ipsec-vpn-server ipsec whack --trafficstatus`  shows live connections, but doesn't show the local lease IP. However according to the Changelog for libreswan, from V3.18 this should be available.

Maybe upgrading Swan ver to V3.20 might solve this. Will check and inform.

**Comment by shankscoder** [comment]
So, the build breaks when changing the SWAN_VER variable in the Dockerfile to 3.19 or 3.20 despite these being valid versions.

For some reason, IPSEC doesn't turn on for these builds, and Pluto doesn't run. 

I'm a bit stumped as to why this is. 

Are you doing anything different in the build to get the container image built and running?

**Comment by hwdsl2** [comment]
@shankscoder Try the original project at https://github.com/hwdsl2/docker-ipsec-vpn-server, which this project is based on, and see if it works for your use case.

The reason is that Libreswan 3.19 and newer require some configuration changes. See: [1] [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/extras/vpnupgrade.sh#L76-L93
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/extras/vpnupgrade.sh#L161-L168

**Comment by shankscoder** [comment]
@hwdsl2 thanks for this. Will try it out.

**Comment by jgimenez** [comment]
Just updated to libreswan 3.21 in here 54fe9b3b84cc51f59d1db9bd488de7eb3bb33dc5

Thanks @hwdsl2 for your contribution!

**Comment by pavelsr** [comment]
Does anyone know is it possible to show list of all connected users ? Ability to identify client will be extremelly useful feature.

For now I saw only possibilities

to see total amount of connected clients: 
`docker exec -it ipsec-vpn-server netstat -i | grep "ppp" | wc -l`

and ip addresses of all connected clients: 
`docker exec -it ipsec-vpn-server ipsec whack --trafficstatus`

But I haven't found the way how to list of connected users. Is it possible ?

**Comment by pavelsr** [comment]
Created a separate issue #6 for it.
