### ISSUE TITLE
Ability to identify client (list of connected users)

### ISSUE THREAD

**Issue by pavelsr** [mobilejazz/docker-ipsec-vpn-server#6]
I have some hosts connected to VPN, each host is logging VPN under separate user .

My task is identify which host is online (connected to VPN) now.

For now I saw only possibilities

to see total amount of connected clients:
docker exec -it ipsec-vpn-server netstat -i | grep "ppp" | wc -l

and ip addresses of all connected clients:
docker exec -it ipsec-vpn-server ipsec whack --trafficstatus

But I haven't found the way how to list of connected users. Is it possible ?

**Comment by jgimenez** [comment]
Have you tried this? https://serverfault.com/questions/495332/how-to-view-pptpd-clients
