### ISSUE TITLE
windows 10 can't connect 

### ISSUE THREAD

**Issue by xiaoyueraymond** [mobilejazz/docker-ipsec-vpn-server#7]
windows 10 can't connect
VPN server is in company
i network nat 192.168.8.59:1701  global ip x.x.x.x ：1701

in linux 
 [root@localhost ~]# netstat -tlun
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8989            0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:25                  :::*                    LISTEN     
udp        0      0 127.0.0.1:323           0.0.0.0:*                          
udp        0      0 0.0.0.0:8989            0.0.0.0:*                          
udp6       0      0 ::1:323                 :::*                               
udp6       0      0 :::4500                 :::*                               
udp6       0      0 :::500                  :::*                               
[root@localhost ~]#

**Comment by janisblaus** [comment]
Hi, i had same issue. Resolved it by following this guide: https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting @xiaoyueraymond check it, i think it will help you as well.
